#!/bin/bash

MODULE="buster"
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' 

is_installed=$(lsmod | grep $MODULE)

make 1>/dev/null 2>&1 || (echo "Error: Module $MODULE could not be compiled" && exit 1)
printf "${GREEN}Module $MODULE compiled${NC}\n"

if [ "$is_installed" != "" ]; then
    printf "${BLUE}Module $MODULE is already installed${NC}\n"
    printf "${BLUE}Removing module $MODULE${NC}\n"
    sudo rmmod $MODULE || (printf "${RED}Error: Module $MODULE could not be removed${NC}\n" && exit 1)
else
    printf "${BLUE}Installing module $MODULE${NC}\n"
    sudo insmod $MODULE.ko || (printf "${RED}Error: Module $MODULE could not be installed${NC}\n" && exit 1)
    printf "${GREEN}Module $MODULE installed${NC}\n"
fi


